### ISSUE TITLE
テストまつだ

### ISSUE THREAD

**Issue by ghost** [dokugaku/all#2]
わいわい

**Comment by yukakawamura** [comment]
川村

**Comment by ghost** [comment]
:thumbsup:

**Comment by kenzan100** [comment]
@mayamatsuda さんは絵文字を覚えた！

**Comment by ghost** [comment]
あ、見られちゃった・・・:ok_woman:

**Comment by ghost** [comment]
すみません、練習していますw

**Comment by kenzan100** [comment]
:smile:

**Comment by kenzan100** [comment]
@mayamatsuda は Issueの閉じ方を覚えた！

**Comment by ghost** [comment]
@kenzan100 先生、お忙しいのにフォローいただきありがとうございます。今週は全然時間がなくて進められていなくてすみません。。。

**Comment by kenzan100** [comment]
見てるので、ご自身のペースで大丈夫ですよー！
